sudo: required
language: python
python:
  - "3.6-dev"  # 3.6 development branch
env:
  - UBUNTU_VER=18.10

install:
  - pip3 install -e .

deploy:
    provider: pypi
    username: $TWINE_USERNAME
    password: $TWINE_PASSWORD
    on:
        tags: true
condition: $UBUNTU_VER = 16.04